import { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Roi, Ruler, RulerDetection, Signal, Simulator, analyseFrame, confirmTwoPointCalibration, confirmMultiPointCalibration, type CalibrationState, type SpatialAnchor } from '@physics-software-sensors/fringelab';
import { FloatingCalculator, RoiOverlay, RulerOverlay } from '@physics-software-sensors/fringelab/react';
import { decodeExperimentImage, RulerDetectionRunner, recognizeRulerReadings, BrowserCameraSource, enumerateVideoInputs, downloadText, rowsToCsv } from '@physics-software-sensors/fringelab/browser';
import '@physics-software-sensors/fringelab/styles.css';
import './style.css';

type Mode = 'roi' | 'ruler' | 'anchors' | 'region';
function App() {
  const canvas = useRef<HTMLCanvasElement>(null), image = useRef<HTMLCanvasElement | null>(null);
  const runner = useRef(new RulerDetectionRunner()), camera = useRef<BrowserCameraSource | null>(null);
  const sourceRevision = useRef(0), operation = useRef(0);
  const [sourceKey, setSourceKey] = useState('sample:0'), [sourceLabel, setSourceLabel] = useState('可复现仿真 · 650 nm'), [size, setSize] = useState({ width: 960, height: 540 });
  const [roi, setRoi] = useState<Roi.RoiGeometry>({ centerX: 480, centerY: 215, width: 820, height: 72, angleDeg: 0 });
  const [ruler, setRuler] = useState<Ruler.RulerCalibration>({ start: { x: 80, y: 420 }, end: { x: 830, y: 420 }, knownLengthMm: 30, originMm: 0 });
  const [mode, setMode] = useState<Mode>('roi'), [calibration, setCalibration] = useState<CalibrationState | null>(null), [anchors, setAnchors] = useState<SpatialAnchor[]>([]), [reading, setReading] = useState(0);
  const [region, setRegion] = useState<RulerDetection.RulerRegion | undefined>(), regionStart = useRef<{ x: number; y: number } | null>(null);
  const [candidate, setCandidate] = useState<RulerDetection.RulerDetectionResult | null>(null), [busy, setBusy] = useState(false), [message, setMessage] = useState('先选择工具，再确认尺标。');
  const [channel, setChannel] = useState<Signal.RequestedProfileChannel>('auto'), [sigma, setSigma] = useState(1.8), [dMm, setDMm] = useState(.25), [distance, setDistance] = useState(1.5), [experiment, setExperiment] = useState<'single' | 'double'>('double'), [aMm, setAMm] = useState(.04);
  const [result, setResult] = useState<ReturnType<typeof analyseFrame> | null>(null), [devices, setDevices] = useState<MediaDeviceInfo[]>([]), [deviceId, setDeviceId] = useState(''), [live, setLive] = useState(false), [cameraSettings, setCameraSettings] = useState('');
  const pixels = useMemo(() => { const c = image.current; return c?.getContext('2d', { willReadFrequently: true })?.getImageData(0,0,c.width,c.height) ?? null; }, [sourceKey]);
  const profile = useMemo(() => pixels ? Signal.extractStripProfile(pixels, { roi, channel }) : null, [pixels, roi, channel]);
  const smooth = useMemo(() => profile ? Signal.gaussianSmooth(profile.profile, sigma) : null, [profile, sigma]);
  const peaks = useMemo(() => smooth ? Signal.detectPeaks(smooth, { minProminence: 2, minDistance: 8, maxPeaks: 30 }) : [], [smooth]);
  const clearCalculation = () => setResult(null);
  const updateRoi = (next: Roi.RoiGeometry) => { setRoi(next); clearCalculation(); };
  const updateRuler = (next: Ruler.RulerCalibration) => { setRuler(next); setCalibration(null); clearCalculation(); };
  const setSource = (next: HTMLCanvasElement, label: string, reset = true) => {
    runner.current.cancel(); operation.current++; sourceRevision.current++; image.current = next;
    setSourceKey(`${label}:${sourceRevision.current}`); setSourceLabel(label); setSize({ width: next.width, height: next.height }); setCalibration(null); setResult(null); setCandidate(null); setAnchors([]); setRegion(undefined); setBusy(false);
    if (reset) { setRoi({ centerX: next.width/2, centerY: next.height*.4, width: next.width*.8, height: Math.max(12,next.height*.12), angleDeg: 0 }); setRuler({ start: { x: next.width*.1, y: next.height*.78 }, end: { x: next.width*.8, y: next.height*.78 }, knownLengthMm: 30, originMm: 0 }); }
  };
  const stopCamera = async () => { await camera.current?.stop(); camera.current = null; setLive(false); };
  const sample = () => {
    void stopCamera();
    const frame = Simulator.simulateDiffraction({ width: 960, height: 540, wavelengthNm: 650, slitSeparationMm: .25, slitWidthMm: .04, screenDistanceM: 1.5, mmPerPixel: .04, noiseStd: .005, saturationLevel: .96, seed: 9173 });
    const c = document.createElement('canvas'); c.width=960;c.height=540;const ctx=c.getContext('2d')!;ctx.putImageData(new ImageData(new Uint8ClampedArray(frame.frame.data),960,540),0,0);
    ctx.fillStyle='#f3efe0';ctx.fillRect(65,400,785,105);ctx.fillStyle='#1a2522';ctx.strokeStyle='#1a2522';ctx.lineWidth=2;ctx.font='20px sans-serif';
    for(let mm=0;mm<=30;mm++){const x=80+mm*25;ctx.beginPath();ctx.moveTo(x,401);ctx.lineTo(x,401+(mm%10===0?45:mm%5===0?31:20));ctx.stroke();if(mm%10===0)ctx.fillText(String(mm/10),x-6,485);}
    setSource(c,'可复现仿真 · 650 nm');setRuler({start:{x:80,y:401},end:{x:830,y:401},knownLengthMm:30,originMm:0});setDMm(.25);setDistance(1.5);setAMm(.04);setExperiment('double');setMessage('合成图含已知 1 mm 刻线，适合演示各模式；不代表真实仪器验证。');
  };
  useEffect(() => { sample(); return () => { operation.current++; runner.current.cancel(); void camera.current?.stop(); }; }, []);
  useEffect(() => { if (!canvas.current || !image.current) return; canvas.current.width=size.width;canvas.current.height=size.height;canvas.current.getContext('2d')?.drawImage(image.current,0,0); }, [sourceKey,size]);
  const safely = async (action: () => void | Promise<void>) => { try { await action(); } catch(error) { if(error instanceof DOMException && error.name==='AbortError')return;setMessage(error instanceof Error ? error.message : String(error)); } };
  const freeze = async () => { await stopCamera(); setCalibration(null); setResult(null); setMessage('当前帧已冻结，请确认这一帧的尺标。'); };
  const startCamera = async () => {
    await stopCamera(); const revision=++sourceRevision.current; const source=new BrowserCameraSource();camera.current=source; source.configure({ deviceId,intervalMs:250 });
    await source.start({runId:'toolkit-demo'});if(camera.current!==source){await source.stop();return;}setLive(true);setCameraSettings(JSON.stringify(source.settings()?.settings));setDevices(await enumerateVideoInputs());
    try { for await(const packet of source.read()) { if(camera.current!==source)break;const c=document.createElement('canvas');c.width=packet.media.width;c.height=packet.media.height;c.getContext('2d')!.putImageData(new ImageData(new Uint8ClampedArray(packet.pixels!.data),c.width,c.height),0,0);setSource(c,`摄像头 ${revision}`,false); } } finally { if(camera.current===source){await source.stop();camera.current=null;setLive(false);} }
  };
  const findRuler = async () => { if(!pixels)return;const key=sourceKey;const job=++operation.current;setBusy(true);setMessage('正在检测刻线…');try { const r=await runner.current.detect(pixels,{sourceType:'image',...(region?{region}:{})});if(job!==operation.current||key!==`${sourceLabel}:${sourceRevision.current}`)return;setCandidate(r);if(r){setRuler(RulerDetection.rulerFromDetection(r));setMode('ruler');setCalibration(null);setResult(null);setMessage(`${r.message}；请核对真实长度，确认后应用。`);}else setMessage('没有可靠刻线候选。请框选尺子，或使用手动/多点标定。'); } finally { if(job===operation.current)setBusy(false); } };
  const ocr = async () => { if(!image.current||!candidate)return;const key=sourceRevision.current;const job=++operation.current;setBusy(true);try { const drafts=await recognizeRulerReadings(image.current,candidate.selectedRegion,'cm',candidate);if(job!==operation.current||key!==sourceRevision.current)return;setAnchors(drafts.anchors);setCandidate({...candidate,numbers:drafts.numbers});setMessage(`OCR 生成 ${drafts.anchors.length} 个待核对点（cm → mm），不会自动应用。`);setMode('anchors'); } finally {if(job===operation.current)setBusy(false);} };
  const confirm = () => { if(live)throw new Error('请先冻结摄像头帧'); const c=mode==='anchors'?confirmMultiPointCalibration(anchors,sourceKey,crypto.randomUUID()):confirmTwoPointCalibration(ruler,sourceKey,crypto.randomUUID());setCalibration(c);setResult(null);setMessage('尺标已确认，参数核对后可计算。'); };
  const calculate = () => { if(!pixels||!calibration||calibration.sourceKey!==sourceKey||live)throw new Error('请先冻结并确认当前图像的尺标');if(!(dMm>0&&distance>0&&aMm>0))throw new Error('请输入正数参数');const scale=calibration.method==='two-point'?Ruler.calculateMmPerPixel(calibration.ruler!)!:1;setResult(analyseFrame(pixels,{experiment,channel,orientation:'vertical',roi,mmPerPixel:scale,spatialAnchors:calibration.anchors,screenDistanceM:distance,slitSeparationMm:dMm,slitWidthMm:aMm,apertureUncertaintyMm:.002,distanceUncertaintyM:.005,calibrationUncertaintyPct:1,referenceWavelengthNm:650,hasReference:false,smoothingSigma:sigma,background:null,measurementReady:true,slitWidthKnown:true})); };
  const clickImage = (event: React.PointerEvent<HTMLDivElement>) => {
    const rect=event.currentTarget.getBoundingClientRect();const point={x:(event.clientX-rect.left)/rect.width*size.width,y:(event.clientY-rect.top)/rect.height*size.height};
    if(mode==='anchors'){setAnchors(a=>[...a,{...point,mm:reading}]);setCalibration(null);setResult(null);setReading(v=>v+10);}
    if(mode==='region'){if(!regionStart.current){regionStart.current=point;setMessage('再点击尺区域的另一角。');}else{const a=regionStart.current;setRegion({x:Math.min(a.x,point.x),y:Math.min(a.y,point.y),width:Math.abs(a.x-point.x),height:Math.abs(a.y-point.y)});regionStart.current=null;setMessage('尺区域已框选，可以检测。');}}
  };
  const yMax=smooth?Math.max(1,...smooth):1;
  return <main><header className="hero"><p className="eyebrow">PHYSICS SOFTWARE SENSORS / TOOLKIT</p><h1>FringeLab 可复用工具台</h1><p>选区、刻度尺、相对响应与光学计算，独立组合使用。</p><div className="fl-row"><FloatingCalculator/><FloatingCalculator title="第二个计算器" triggerLabel="打开第二个计算器"/></div></header>
    <section className="fl-surface panel"><div className="fl-row"><h2>1 · 输入与测量工具</h2><button className="fl-button" onClick={sample}>载入示例</button><label className="fl-button">导入图片<input aria-label="导入图片" type="file" accept="image/*,.heic,.heif" onChange={event=>{const file=event.target.files?.[0];if(file)void safely(async()=>{await stopCamera();sourceRevision.current++;setCalibration(null);setResult(null);runner.current.cancel();const generation=sourceRevision.current;const decoded=await decodeExperimentImage(file);if(generation!==sourceRevision.current)return;const c=document.createElement('canvas');c.width=decoded.naturalWidth;c.height=decoded.naturalHeight;c.getContext('2d')!.drawImage(decoded,0,0);setSource(c,file.name);});event.target.value='';}}/></label></div>
      <div className="fl-row camera-row"><select aria-label="摄像头设备" value={deviceId} onChange={e=>setDeviceId(e.target.value)}><option value="">默认摄像头</option>{devices.map(d=><option key={d.deviceId} value={d.deviceId}>{d.label||d.deviceId}</option>)}</select><button className="fl-button" onClick={()=>void safely(startCamera)} disabled={live}>启动摄像头</button><button className="fl-button" onClick={()=>void safely(freeze)} disabled={!live}>冻结/断开</button><button className="fl-button" disabled={!live} onClick={()=>void safely(async()=>{const s=await camera.current?.lockSettings();setCameraSettings(JSON.stringify(s?.settings));})}>尝试锁定设置</button></div>
      {cameraSettings&&<p className="fl-note">实际相机设置：{cameraSettings}</p>}<p className="fl-note">{sourceLabel} · {size.width} × {size.height} · 原图采样</p>
      <div className="tools" role="group" aria-label="图像工具">{(['roi','ruler','anchors','region']as const).map((value,i)=><button key={value} className={`fl-button ${mode===value?'fl-primary':''}`} onClick={()=>{setMode(value);regionStart.current=null;}}>{['旋转 ROI','手动虚拟尺','多点尺标','框选实物尺'][i]}</button>)}</div>
      <div className="image-stage" style={{aspectRatio:`${size.width}/${size.height}`}} onPointerDown={clickImage}><canvas ref={canvas}/><RoiOverlay roi={roi} size={size} interactive={mode==='roi'} onChange={updateRoi}/>{mode==='ruler'&&<RulerOverlay ruler={ruler} size={size} detection={candidate} onChange={updateRuler}/>}<svg className="fl-overlay" viewBox={`0 0 ${size.width} ${size.height}`}>{anchors.map((p,i)=><g key={i}><circle cx={p.x} cy={p.y} r={8} fill="#ffd15a"/><text x={p.x+12} y={p.y-12} fill="#fff" stroke="#112c24" paintOrder="stroke" strokeWidth={4} fontSize={18}>{p.mm} mm</text></g>)}{region&&<rect x={region.x} y={region.y} width={region.width} height={region.height} fill="none" stroke="#ffd15a" strokeWidth={3}/>}</svg></div>
      <div className="fields"><label>ROI 角度 (°)<input type="number" value={roi.angleDeg} onChange={e=>updateRoi({...roi,angleDeg:Number(e.target.value)})}/></label><label>已知尺长 (mm)<input type="number" value={ruler.knownLengthMm} onChange={e=>updateRuler({...ruler,knownLengthMm:Number(e.target.value)})}/></label><label>尺起始读数 (mm)<input type="number" value={ruler.originMm??0} onChange={e=>updateRuler({...ruler,originMm:Number(e.target.value)})}/></label><label>下一点读数 (mm)<input type="number" value={reading} onChange={e=>setReading(Number(e.target.value))}/></label></div>
      <div className="fl-row"><button className="fl-button" onClick={()=>void safely(findRuler)} disabled={busy||live}>自动检测刻线</button><button className="fl-button" onClick={()=>{operation.current++;runner.current.cancel();setBusy(false);setMessage('任务已取消，保留人工标定模式。');}} disabled={!busy}>取消检测</button><button className="fl-button" onClick={()=>void safely(ocr)} disabled={!candidate||busy||live}>OCR 候选（厘米数字）</button><button className="fl-button" onClick={()=>{setAnchors([]);setCalibration(null);setResult(null);}}>清除尺标点</button><button className="fl-button fl-primary" onClick={()=>void safely(confirm)} disabled={live}>核对并应用尺标</button></div>
      {anchors.length>0&&<div className="anchor-list">{anchors.map((p,i)=><label key={i}>点 {i+1}<input aria-label={`尺标点 ${i+1} mm`} type="number" value={p.mm} onChange={e=>{setAnchors(a=>a.map((v,j)=>j===i?{...v,mm:Number(e.target.value)}:v));setCalibration(null);setResult(null);}}/><button className="fl-button" onClick={()=>{setAnchors(a=>a.filter((_,j)=>j!==i));setCalibration(null);setResult(null);}}>移除</button></label>)}</div>}
      <p className="status" role="status">{message}</p><p className="fl-note" data-testid="calibration-status">{calibration?'当前图像尺标：已确认':'当前图像尺标：未确认'}。自动识别和 OCR 均为候选；可以直接使用手动与多点模式。</p>
    </section>
    <section className="fl-surface panel"><h2>2 · 相对响应剖面与信号特征</h2><div className="fields"><label>通道<select value={channel} onChange={e=>{setChannel(e.target.value as Signal.RequestedProfileChannel);setResult(null);}}>{['auto','r','g','b','luminance'].map(c=><option key={c}>{c}</option>)}</select></label><label>平滑 σ (px)<input type="number" min="0" max="10" step=".1" value={sigma} onChange={e=>{setSigma(Math.max(0,Number(e.target.value)));setResult(null);}}/></label></div>
      <svg className="profile" viewBox="0 0 900 220" role="img" aria-label="相对响应曲线"><path d={smooth?Array.from(smooth,(v,i)=>`${i?'L':'M'} ${i/(smooth.length-1)*900} ${205-v/yMax*185}`).join(' '):''} fill="none" stroke="#0c8f75" strokeWidth={2}/>{peaks.map(p=><circle key={p.index} cx={p.position/(smooth!.length-1)*900} cy={205-p.value/yMax*185} r={4} fill="#cf7a16"/>)}</svg><p className="fl-note">通道 {profile?.selectedChannel} · {peaks.length} 个局部亮峰 · 饱和 {((profile?.saturationRates[profile.selectedChannel]??0)*100).toFixed(2)}%。纵轴为相对相机响应，不是 lux 或 W/m²。</p>
      <div className="fl-row"><button className="fl-button" onClick={()=>downloadText(JSON.stringify({source:sourceLabel,sourceKey,roi,calibration,profile:profile?Array.from(profile.profile):[],axisPx:profile?Array.from(profile.axisPositionsPx):[],selectedChannel:profile?.selectedChannel,saturationByChannel:profile?.saturationRates,peaks,result},null,2),'fringelab-toolkit.json','application/json')}>导出 JSON</button><button className="fl-button" onClick={()=>{if(profile)downloadText(rowsToCsv(['axis_px','response_dn'],Array.from(profile.profile,(v,i)=>[profile.axisPositionsPx[i]!,v])),'profile.csv','text/csv');}}>导出 CSV</button></div>
    </section>
    <section className="fl-surface panel"><h2>3 · 光学反演（配套处理工具）</h2><div className="fields"><label>实验<select value={experiment} onChange={e=>{setExperiment(e.target.value as 'single'|'double');setResult(null);}}><option value="double">双缝亮纹</option><option value="single">单缝暗纹</option></select></label><label>双缝中心距 d (mm)<input type="number" step=".01" value={dMm} onChange={e=>{setDMm(Number(e.target.value));setResult(null);}}/></label><label>缝屏距 L (m)<input type="number" step=".01" value={distance} onChange={e=>{setDistance(Number(e.target.value));setResult(null);}}/></label><label>单缝宽 a (mm)<input type="number" step=".01" value={aMm} onChange={e=>{setAMm(Number(e.target.value));setResult(null);}}/></label></div><button className="fl-button fl-primary" onClick={()=>void safely(calculate)} disabled={!calibration||live}>核对参数并计算</button><output className="measurement" aria-live="polite">{result?`${result.status} · λ ${result.wavelengthNm?.toFixed(2)??'—'} nm · Δx ${result.fringeSpacingMm?.toFixed(3)??'—'} mm`:'等待当前图像的尺标确认与主动计算'}</output>{result?.warnings.map(w=><p className="fl-note" key={w}>{w}</p>)}<p className="fl-note">修改参数/选区或换图后清除旧计算。默认误差输入用于演示，请按真实器材修改或直接使用 core API。</p></section>
    <footer>全部分析在浏览器本地完成。OCR 首次使用需下载语言模型；没有照片上传服务。</footer>
  </main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
